USE [ForumUa]
GO

/****** Object:  Table [dbo].[Mark]    Script Date: 08.02.2022 8:59:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Mark](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PostId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[PostMark] [int] NOT NULL,
 CONSTRAINT [PK_Mark] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Mark]  WITH CHECK ADD  CONSTRAINT [FK_Mark_User1] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO

ALTER TABLE [dbo].[Mark] CHECK CONSTRAINT [FK_Mark_User1]
GO

ALTER TABLE [dbo].[Mark]  WITH CHECK ADD  CONSTRAINT [CK__Mark__PostMark__619B8048] CHECK  (([PostMark]<=(1) AND [PostMark]>=(-1)))
GO

ALTER TABLE [dbo].[Mark] CHECK CONSTRAINT [CK__Mark__PostMark__619B8048]
GO


